import React,{ useState, useEffect, useContext } from "react";

export default (props:any) => {
  return(
  	<>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	  <p>set-2</p>
  	</>
  )
}